-- MySQL Script generated by MySQL Workbench
-- Thu Sep 13 20:15:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bamazon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bamazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bamazon` DEFAULT CHARACTER SET latin1 ;
USE `bamazon` ;

-- -----------------------------------------------------
-- Table `bamazon`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bamazon`.`products` ;

CREATE TABLE IF NOT EXISTS `bamazon`.`products` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(50) NULL DEFAULT NULL,
  `department_name` VARCHAR(50) NULL DEFAULT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  `stock_quantity` INT(11) NULL DEFAULT NULL,
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
